### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by NimaVibeVans** [LinkedInLearning/react-spas-774920#4]
[2019-09-10T23_29_40_371Z-debug.log](https://github.com/LinkedInLearning/react-spas-774920/files/3598145/2019-09-10T23_29_40_371Z-debug.log)

**Comment by NimaVibeVans** [comment]
Resolved using:
sudo npm install -g npm@latest 
rm -rf node_modules
npm install 
npm start

**Comment by planetoftheweb** [comment]
You probably just had an old version of node.js installed, which caused the problem. It's good to keep that updated from time to time.
