### ISSUE TITLE
Error with npm install

### ISSUE THREAD

**Issue by purringpigeon** [LinkedInLearning/react-spas-774920#5]
Hello,

I have been attempting some of your courses to get a handle on react and spring boot to build out some new architecture.  I was hoping to see how to learn a little more on authentication with this course.  I followed the steps (Windows 10 machine with Eclipse) and created the folder on the desktop, performed the git commands and saw all the branches.  When I did the npm install I got the following error - and I am unable to continue on. 

$ npm install
npm ERR! code EINTEGRITY
npm ERR! sha1-dTHjnUlJwoGma4xabgJl6LBYlNo= integrity checksum failed when using sha1: wanted sha1-dTHjnUlJwoGma4xabgJl6LBYlNo= but got sha512-Vj
Fo4P5Whtj4vsLzsYBu5ayHhoHJ0UqNm7ibvShmbmoz7tGi0vXaoJbGdB+GmDMLUdg8DpQXEIeVDAe8MaABvQ== sha1-OL6/gMMiCopIe2/Ps5QbsRcgwUU=. (2829 bytes)

Wondering if something changed or if I missed a step. 

Thank you.

**Comment by planetoftheweb** [comment]
Hmm. That's a new one for me. Try deleting the package-lock.json file and see if that works. I don't think it's a problem with the course, it might be something to do with the way the installation is being attempted. Also try a linux terminal. I'm going to close this, but feel free to open it back if you figure it out or for anything else.
